### ISSUE TITLE
Compiler complains about inline...

### ISSUE THREAD

**Issue by 0b1kn00b** [haxetink/tink_io#1]
```
tink/io/Progress.hx:23: characters 22-58 : Inline variable initialization must be a constant value.
```

Not sure which version of Haxe I'm running atm. Ping me and I'll dig in and look

**Comment by back2dos** [comment]
Yup, this is an issue with recent Haxe builds. FWIW it does work with the latest stable. I wanted to bring it up with Simn when he calls the feature freeze for 3.3. (should be mid-march). In the mean time I suggest replacing the `inline` with a `(default, null)`.

**Comment by back2dos** [comment]
This was fixed in the Haxe compiler.

**Comment by 0b1kn00b** [comment]
Thanks for the heads up.
