### ISSUE TITLE
StreamParser eof

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_io#23]
https://github.com/haxetink/tink_io/commit/4c4dc3ee88e06efff9ca15f5222c6f3cf052939d#diff-9c9d45e7ba3bb2121d3006aeb61d4d9bR59

The above change was to mitigate a situation where `consume` is called more than once, even it returned `{resume: false}`. It happens when the stream has already been depleted when `consume` is called.

stepwise:
1. Parser parses the last chunk in the stream and emits `Done`
1. `consume()` is called
1. `forEach` ends with `Depleted` instead of `Halted` (yeah, even the handler emits `Finish`)
1. `consume` is called again

Not sure if the `null` check is a proper fix. Maybe something should be done in the `doParse` function instead.

**Comment by back2dos** [comment]
Hmmm. This is an intersting point:

> `forEach` ends with `Depleted` instead of `Halted` (yeah, even the handler emits `Finish`)

Instead we could yield `Halted` with a depleted rest. That does give the caller one more case to care about, but at least it doesn't swallow information. What do you think?

One way or the other, we should handle that problem internally by avoiding to call `consume` after it returned `{ resume: false }`.

**Comment by kevinresol** [comment]
> That does give the caller one more case to care about, but at least it doesn't swallow information.

Shouldn't be a big deal I guess? Because I think it is more natural for handlers that emit Finish to expect more instead of expecting Depleted. It will be very likely for me to write this:

```haxe
stream.forEach(function(_) return Finish).handle(function() switch o {
  case Depleted; throw 'unreachable';
  case Halted(_): // expected
  default: // errors
});
```

**Comment by back2dos** [comment]
Ok. Well then, let's make sure we emit `Halted`.

**Comment by kevinresol** [comment]
> case Depleted; throw 'unreachable';

Well, second thought on this: This is wrong because the handler can never get run if the stream is empty. So let's just hold the change and fix the usage first.

**Comment by kevinresol** [comment]
Please review: https://github.com/haxetink/tink_io/commit/c9f3b3e1335df89009b39fd52c4151fbf818f954

**Comment by back2dos** [comment]
The change seems fine.

I really need to clean up that function though :D

**Comment by kevinresol** [comment]
Not sure if it is a problem:

Say I have a stream parser that transform a `Source` into `Stream<Int>` like this

```haxe
source.parseStream(new SimpleBytewiseParser(function(c) return Done(c)));
```

This will always give `-1` as the last stream item. There seems no way to tell `eof()` that we can safely end the parsing without a result. Because eof either results in a error from `Progressed`/`Failed(err)`, or emits a result from `Done(data)`.

**Comment by back2dos** [comment]
Hmm, I suppose for the pure branch we can check if the remaining source is `depleted` after an item is done and end the stream right there.

**Comment by kevinresol** [comment]
> Hmm, I suppose for the pure branch we can check if the remaining source is depleted after an item is done and end the stream right there.

I don't quite get that...

**Comment by kevinresol** [comment]
So do you mean we don't have to `eof()` at all?

**Comment by kevinresol** [comment]
Ignore me, I think I figured out the fix

**Comment by kevinresol** [comment]
As at fdd03c8, if the parser keep emitting `Progressed` til the end of source. The parsed result will be `null`, and the `eof()` function is not called. Because it went into [this branch](https://github.com/haxetink/tink_io/blob/fdd03c8/src/tink/io/StreamParser.hx#L73)

**Comment by kevinresol** [comment]
Looks like after updating the dependencies this is broken again: https://travis-ci.org/haxetink/tink_io/jobs/399863230#L580

**Comment by kevinresol** [comment]
I think this is done now.
