### ISSUE TITLE
Consider merging pure branch and start proper documentations

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_io#29]
From time to time people come and ask what `pure` is, because we usually recommend people to use it. Mostly because we have all new features & bug fixes on pure branch only now. I suppose we should merge pure and properly document what targets are supported. From my understanding they should include node and php (and sys with runloop?).

Any objections? @back2dos @ciscoheat @gene-pavlovsky @benmerckx

**Comment by back2dos** [comment]
Yeah, I was a bit reluctant to merge, because it'll most likely break java, cs and quite possibly neko. But I think we should move ahead now and fix problems when people start complaining.

**Comment by gene-pavlovsky** [comment]
Personal opinion: Don't be afraid to break stuff. If you're too conservative, progress will be too slow. Let people complain when things break, or better yet, they might submit PRs to fix the broken parts.

**Comment by kevinresol** [comment]
It is nighttime here, and I will do the following in the next morning:

1. rename `master` as `old`
2. rename `pure` as `master`
3. force push the new `master`

I think this is the best way to preserve the history

**Comment by gene-pavlovsky** [comment]
Is this a good practice? Why not just merge to master?

**Comment by benmerckx** [comment]
You could use a git merge strategy as outlined here: https://stackoverflow.com/a/2763118/5872160

**Comment by kevinresol** [comment]
I know that, but we don't really want a "merge", but complete replacement.

e.g. we don't want old code, which is not part of `pure`, to stay. For instance the `Buffer` class in master is completely gone in `pure`. If we "merge", it will stay.

**Comment by kevinresol** [comment]
Ok, after a shower my mind is back. Maybe it works, because merging should also bring in the "delete Buffer class" commit for example.

**Comment by kevinresol** [comment]
https://github.com/haxetink/tink_io/pull/32
https://github.com/haxetink/tink_web/pull/65
https://github.com/haxetink/tink_http/pull/99
https://github.com/haxetink/tink_cli/pull/11
https://github.com/benmerckx/asys/pull/6

anything else?

**Comment by gene-pavlovsky** [comment]
These have failing CI checks:
https://github.com/haxetink/tink_io/pull/32
https://github.com/haxetink/tink_cli/pull/11
https://github.com/benmerckx/asys/pull/6
Is that ok? :)
