### ISSUE TITLE
Order of arguments for ofInput/ofOutput and ofNodeStream

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_io#3]
I think it might not be too late to give these methods the same order of arguments.
Right now I'm writing stuff like this:

``` haxe
#if nodejs
input = Source.ofNodeStream(socket, 'socket input');
output = Sink.ofNodeStream(socket, 'socket output');
#else
input = Source.ofInput('socket input', socket.input);
output = Sink.ofOutput('socket output', socket.output);
#end
```

Where it kind of feels like name should either come first or last in all of those methods?

**Comment by back2dos** [comment]
You are right of course. I generally wanted to enforce the naming of sources and sinks. This normalization should fall out as a side effect.

**Comment by back2dos** [comment]
Meh, this is tedious. For now I think I'll just change the parameter order. I guess that'll break some of your code. When is a good time for you?

**Comment by benmerckx** [comment]
Whenever you like. When I see a new release I'll update my stuff.

**Comment by back2dos** [comment]
Ok, now everything is updated on haxelib.
