### ISSUE TITLE
Slice of WrappedBuffer

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_io#39]
Copy paste of my gitter monologue so I don't forget:

````haxe
trace(part.length);
trace(remaining.length);
var sliced = part.slice(0, part.length - remaining.length);
trace(sliced.length);
````
If part and remaining are Chunks, the following shouldn't happen, right?
````haxe
src/smtpmailer/MultipartEncoder.hx:52: 3292
src/smtpmailer/MultipartEncoder.hx:53: 1
src/smtpmailer/MultipartEncoder.hx:55: 3
````
Remaining is a `tink.io.nodejs.WrappedBuffer`, part is a `CompoundChunk` over two of those. I think this happens because a `CompoundChunk`'s slice method expects the slices to deal with from and to values that can be larger or smaller than their start/length. (At least that's what it seems like if I look at `ByteChunk`). But as far as I can tell `WrappedBuffer` doesn't deal with that situation.

If I copy `ByteChunk`'s way of dealing with slices into `WrappedBuffer` I get expected results. I'll see if I can open a PR with this.

**Comment by kevinresol** [comment]
Perhaps this WrappedBuffer can be move to tink_chunk altogether (maybe rename as `NodeBufferChunk`) and make [the conversion](https://github.com/haxetink/tink_chunk/blob/163f5be0a9a7fa964e6cbee0cc051376ced35c99/src/tink/Chunk.hx#L136) slightly more efficient
