### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_io#4]
I've been trying to write a parser but wasn't getting anywhere. Parsing steps worked, but I never got the result. But when I tried the latest git version everything I've been trying suddenly works. So, might be time to update haxelib?

**Comment by back2dos** [comment]
Done ;)

**Comment by kevinresol** [comment]
omg this seems to fix https://github.com/haxetink/tink_http/issues/9, has spent a few hours figuring out why -__-
